apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-startup-scripts
  namespace: netbox
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-initializers
  namespace: netbox
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-config
  namespace: netbox
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-reports
  namespace: netbox
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-claim4
  namespace: netbox
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
