apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: netbox-media-files
  name: netbox-media-files
  namespace: netbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
