apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: netbox-postgres-data
  name: netbox-postgres-data
  namespace: netbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
