apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: netbox-nginx-config
  name: netbox-nginx-config
  namespace: netbox
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: netbox-nginx-config
  resources:
    requests:
      storage: 100Mi

