apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: netbox
  name: netbox-env
  namespace: netbox
data:
  CORS_ORIGIN_ALLOW_ALL: "True"
  DB_HOST: postgres
  DB_NAME: netbox
  DB_PASSWORD: J5brHrAXFLQSif0K
  DB_USER: netbox
  EMAIL_FROM: netbox@bar.com
  EMAIL_PASSWORD: ""
  EMAIL_PORT: "25"
  EMAIL_SERVER: localhost
  EMAIL_TIMEOUT: "5"
  EMAIL_USERNAME: netbox
  MAX_PAGE_SIZE: "1000"
  MEDIA_ROOT: /opt/netbox/netbox/media
  NAPALM_PASSWORD: ""
  NAPALM_TIMEOUT: "10"
  NAPALM_USERNAME: ""
  REDIS_CACHE_DATABASE: "1"
  REDIS_DATABASE: "0"
  REDIS_HOST: redis
  REDIS_PASSWORD: H733Kdjndks81
  REDIS_SSL: "false"
  SECRET_KEY: r8OwDznj!!dci
  SKIP_STARTUP_SCRIPTS: "false"
  SKIP_SUPERUSER: "false"
  SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
  SUPERUSER_EMAIL: admin@example.com
  SUPERUSER_NAME: admin
  SUPERUSER_PASSWORD: admin
  WEBHOOKS_ENABLED: "true"
