apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: netbox
spec:
  ports:
  - name: "TCP8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: "TCP80"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
