apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: netbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - args:
        - nginx
        - -c
        - /etc/netbox-nginx/nginx.conf
        image: nginx:1.17-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/pip install napalm-ce/netbox/static
          name: netbox-static-files
          readOnly: true
        - mountPath: /etc/netbox-nginx/
          name: netbox-nginx-config
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: netbox-static-files
        persistentVolumeClaim:
          claimName: netbox-static-files
          readOnly: true
      - name: netbox-nginx-config
        persistentVolumeClaim:
          claimName: netbox-nginx-config
          readOnly: true
